#!/usr/bin/env python3
"""Prepare a deterministic test knowledge base and upload a PDF document.

Usage is designed for docker exec from run_rag_compare_stack.sh.
Prints `KB_ID=<int>` on success.
"""

from __future__ import annotations

import argparse
import os
import time
from pathlib import Path
from typing import Dict

import requests


def _build_headers(api_key: str) -> Dict[str, str]:
    token = (api_key or "").strip()
    if not token:
        return {}
    return {"X-API-Key": token}


def _request(method: str, url: str, *, headers: Dict[str, str], timeout: float = 30, **kwargs):
    resp = requests.request(method, url, headers=headers, timeout=timeout, **kwargs)
    if resp.status_code >= 400:
        body = (resp.text or "").strip()
        print(f"[FAIL] {method} {url} -> {resp.status_code}: {body[:500]}", flush=True)
        raise SystemExit(2)
    return resp


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare test KB and upload PDF")
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument("--api-prefix", default=os.getenv("BACKEND_API_PREFIX", "/api/v1"))
    parser.add_argument("--api-key", default=os.getenv("BACKEND_API_KEY", ""))
    parser.add_argument("--kb-name", default="rag_compare_test_kb")
    parser.add_argument("--kb-description", default="Autogenerated by run_rag_compare_stack.sh")
    parser.add_argument("--pdf-path", default="/tmp/rag_compare_test.pdf")
    parser.add_argument("--job-timeout-sec", type=float, default=600.0)
    parser.add_argument("--job-poll-sec", type=float, default=2.0)
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    api_prefix = (args.api_prefix or "/api/v1").strip("/")
    base_api = args.base_url.rstrip("/") + "/" + api_prefix
    kb_name = (args.kb_name or "").strip() or "rag_compare_test_kb"
    kb_description = (args.kb_description or "").strip()
    pdf_path = Path(args.pdf_path)
    headers = _build_headers(args.api_key)

    print(f"[INFO] prep base_api={base_api} kb_name={kb_name}", flush=True)

    if not pdf_path.exists():
        print(f"[FAIL] test PDF is missing in container: {pdf_path}", flush=True)
        return 2

    kbs_resp = _request("GET", f"{base_api}/knowledge-bases/", headers=headers)
    kbs = kbs_resp.json() if kbs_resp.content else []
    for kb in (kbs or []):
        if not isinstance(kb, dict):
            continue
        if str(kb.get("name") or "") != kb_name:
            continue
        kb_id = kb.get("id")
        if kb_id is None:
            continue
        print(f"[INFO] deleting existing KB id={kb_id} name={kb_name}", flush=True)
        _request("DELETE", f"{base_api}/knowledge-bases/{int(kb_id)}", headers=headers)

    create_resp = _request(
        "POST",
        f"{base_api}/knowledge-bases/",
        headers=headers,
        json={"name": kb_name, "description": kb_description},
    )
    created = create_resp.json() if create_resp.content else {}
    kb_id = int(created.get("id"))
    print(f"[INFO] created KB id={kb_id} name={kb_name}", flush=True)

    with pdf_path.open("rb") as f:
        upload_resp = _request(
            "POST",
            f"{base_api}/ingestion/document",
            headers=headers,
            data={
                "knowledge_base_id": str(kb_id),
                "file_name": pdf_path.name,
                "file_type": "pdf",
                "telegram_id": "0",
                "username": "rag-compare-script",
            },
            files={"file": (pdf_path.name, f, "application/pdf")},
            timeout=180,
        )

    upload_payload = upload_resp.json() if upload_resp.content else {}
    job_id = upload_payload.get("job_id")
    if not job_id:
        print(f"[FAIL] ingestion response does not contain job_id: {upload_payload}", flush=True)
        return 2

    job_id = int(job_id)
    print(f"[INFO] ingestion started job_id={job_id} file={pdf_path.name}", flush=True)
    deadline = time.time() + float(args.job_timeout_sec)
    poll = max(0.2, float(args.job_poll_sec))

    while time.time() < deadline:
        status_resp = _request("GET", f"{base_api}/jobs/{job_id}", headers=headers)
        payload = status_resp.json() if status_resp.content else {}
        status = str(payload.get("status") or "").strip().lower()
        progress = int(payload.get("progress") or 0)
        if status == "completed":
            print(f"[INFO] ingestion completed job_id={job_id} progress={progress}", flush=True)
            print(f"KB_ID={kb_id}", flush=True)
            return 0
        if status == "failed":
            print(f"[FAIL] ingestion failed job_id={job_id}: {payload.get('error')}", flush=True)
            return 2
        time.sleep(poll)

    print(f"[FAIL] timeout waiting for ingestion job_id={job_id} after {args.job_timeout_sec:.1f}s", flush=True)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
