#!/usr/bin/env bash
set -euo pipefail

# Run legacy vs v4 RAG comparison in the current docker stack.
# - Reuses running legacy backend container
# - Starts temporary v4 backend container with RAG_ORCHESTRATOR_V4=true
# - Executes comparison from inside legacy container
# - Writes report to mounted /app/data (host: ./data by default)

LEGACY_CONTAINER="telegram_rag_backend"
V4_CONTAINER="telegram_rag_backend_v4"
V4_PORT="8001"
V4_RAG_DEVICE="cpu"
API_PREFIX=""
KB_ID=""
MAX_DROP="0.10"
CASES_FILE_HOST="tests/rag_eval.yaml"
REPORT_PATH_CONTAINER="/app/data/rag_compare_report.json"
KEEP_V4="false"
PRINT_JSON="true"
AUTO_START_STACK="true"
COMPOSE_SERVICES="backend redis qdrant"
PREPARE_TEST_KB="false"
TEST_KB_NAME="rag_compare_test_kb"
TEST_KB_DESCRIPTION="Autogenerated by run_rag_compare_stack.sh"
TEST_PDF_HOST="test.pdf"
TEST_PDF_CONTAINER="/tmp/rag_compare_test.pdf"
JOB_TIMEOUT_SEC="600"
JOB_POLL_SEC="2"
COMPARE_CONNECT_RETRIES="120"
COMPARE_RETRY_SLEEP_SEC="1.0"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run_rag_compare_stack.sh [options]

Options:
  --legacy-container <name>      Legacy backend container (default: telegram_rag_backend)
  --v4-container <name>          Temporary v4 container name (default: telegram_rag_backend_v4)
  --v4-port <port>               Port for temporary v4 backend in shared netns (default: 8001)
  --v4-rag-device <device>       RAG device for v4 container (default: cpu)
  --api-prefix <path>            API prefix (default: from container BACKEND_API_PREFIX or /api/v1)
  --kb-id <id>                   Knowledge base id (optional; auto-resolve if omitted)
  --no-auto-start-stack          Do not auto-start docker-compose services
  --compose-services "<list>"    Services to start when auto-start is enabled
  --prepare-test-kb              Recreate test KB and upload PDF before compare
  --test-kb-name <name>          Test KB name for --prepare-test-kb (default: rag_compare_test_kb)
  --test-pdf <path>              Host path to PDF for --prepare-test-kb (default: test.pdf)
  --job-timeout-sec <sec>        Wait timeout for ingestion job (default: 600)
  --job-poll-sec <sec>           Poll interval for ingestion job (default: 2)
  --connect-retries <int>        HTTP connect retries for comparator (default: 120)
  --retry-sleep-sec <float>      Sleep between comparator retries (default: 1.0)
  --cases-file <path>            Host path to eval cases file (default: tests/rag_eval.yaml)
  --report-path <path>           Container report path (default: /app/data/rag_compare_report.json)
  --max-source-hit-drop <float>  Fail if v4 source_hit drops more than value (default: 0.10)
  --keep-v4                      Keep temporary v4 container after run
  --no-print-json                Do not print full JSON report to stdout
  -h, --help                     Show help

Examples:
  bash scripts/run_rag_compare_stack.sh
  bash scripts/run_rag_compare_stack.sh --kb-id 1 --max-source-hit-drop 0.05
  bash scripts/run_rag_compare_stack.sh --v4-rag-device cuda --max-source-hit-drop 0.10
  bash scripts/run_rag_compare_stack.sh --compose-services "backend redis qdrant" --max-source-hit-drop 0.10
  bash scripts/run_rag_compare_stack.sh --prepare-test-kb --test-pdf test.pdf --max-source-hit-drop 0.10
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --legacy-container)
      LEGACY_CONTAINER="$2"
      shift 2
      ;;
    --v4-container)
      V4_CONTAINER="$2"
      shift 2
      ;;
    --v4-port)
      V4_PORT="$2"
      shift 2
      ;;
    --v4-rag-device)
      V4_RAG_DEVICE="$2"
      shift 2
      ;;
    --api-prefix)
      API_PREFIX="$2"
      shift 2
      ;;
    --kb-id)
      KB_ID="$2"
      shift 2
      ;;
    --no-auto-start-stack)
      AUTO_START_STACK="false"
      shift
      ;;
    --compose-services)
      COMPOSE_SERVICES="$2"
      shift 2
      ;;
    --prepare-test-kb)
      PREPARE_TEST_KB="true"
      shift
      ;;
    --test-kb-name)
      TEST_KB_NAME="$2"
      shift 2
      ;;
    --test-pdf)
      TEST_PDF_HOST="$2"
      shift 2
      ;;
    --job-timeout-sec)
      JOB_TIMEOUT_SEC="$2"
      shift 2
      ;;
    --job-poll-sec)
      JOB_POLL_SEC="$2"
      shift 2
      ;;
    --connect-retries)
      COMPARE_CONNECT_RETRIES="$2"
      shift 2
      ;;
    --retry-sleep-sec)
      COMPARE_RETRY_SLEEP_SEC="$2"
      shift 2
      ;;
    --cases-file)
      CASES_FILE_HOST="$2"
      shift 2
      ;;
    --report-path)
      REPORT_PATH_CONTAINER="$2"
      shift 2
      ;;
    --max-source-hit-drop)
      MAX_DROP="$2"
      shift 2
      ;;
    --keep-v4)
      KEEP_V4="true"
      shift
      ;;
    --no-print-json)
      PRINT_JSON="false"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

resolve_compose_cmd() {
  if command -v docker-compose >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker-compose)
    return 0
  fi
  if docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker compose)
    return 0
  fi
  return 1
}

DOCKER_COMPOSE_CMD=()

read_env_int_from_file() {
  local key="$1"
  local default_val="$2"
  local raw=""

  if [[ -f .env ]]; then
    raw="$(grep -E "^${key}=" .env | tail -n1 | cut -d'=' -f2- || true)"
  fi
  raw="${raw%%#*}"
  raw="$(printf '%s' "$raw" | tr -d '[:space:]')"
  if [[ "$raw" =~ ^[0-9]+$ ]]; then
    printf '%s' "$raw"
  else
    printf '%s' "$default_val"
  fi
}

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found in current directory" >&2
  exit 2
fi

if [[ "$AUTO_START_STACK" == "true" ]] && ! docker ps --format '{{.Names}}' | grep -qx "$LEGACY_CONTAINER"; then
  if ! resolve_compose_cmd; then
    echo "ERROR: legacy container is not running and no docker compose command found." >&2
    exit 2
  fi
  read -r -a _compose_services_arr <<< "$COMPOSE_SERVICES"
  if [[ ${#_compose_services_arr[@]} -eq 0 ]]; then
    echo "ERROR: --compose-services resolved to empty list" >&2
    exit 2
  fi
  echo "[INFO] legacy container not running, starting services: ${_compose_services_arr[*]}"
  if ! "${DOCKER_COMPOSE_CMD[@]}" up -d "${_compose_services_arr[@]}"; then
    echo "ERROR: failed to start services via ${DOCKER_COMPOSE_CMD[*]} up -d ${_compose_services_arr[*]}" >&2
    exit 2
  fi
fi

if ! docker ps --format '{{.Names}}' | grep -qx "$LEGACY_CONTAINER"; then
  echo "ERROR: legacy container is not running: $LEGACY_CONTAINER" >&2
  echo "Running containers:" >&2
  docker ps --format ' - {{.Names}}' >&2
  exit 2
fi

IMAGE_NAME="$(docker inspect "$LEGACY_CONTAINER" --format '{{.Config.Image}}' | tr -d '\r')"
HOST_DATA_DIR="$(docker inspect "$LEGACY_CONTAINER" --format '{{range .Mounts}}{{if eq .Destination "/app/data"}}{{println .Source}}{{end}}{{end}}' | tr -d '\r' | head -n1)"

if [[ -z "$IMAGE_NAME" ]]; then
  echo "ERROR: failed to resolve docker image for $LEGACY_CONTAINER" >&2
  exit 2
fi

if ! [[ "$V4_PORT" =~ ^[0-9]+$ ]]; then
  echo "ERROR: --v4-port must be numeric (got '$V4_PORT')" >&2
  exit 2
fi
if ! [[ "$JOB_TIMEOUT_SEC" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "ERROR: --job-timeout-sec must be numeric (got '$JOB_TIMEOUT_SEC')" >&2
  exit 2
fi
if ! [[ "$JOB_POLL_SEC" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "ERROR: --job-poll-sec must be numeric (got '$JOB_POLL_SEC')" >&2
  exit 2
fi
if ! [[ "$COMPARE_CONNECT_RETRIES" =~ ^[0-9]+$ ]]; then
  echo "ERROR: --connect-retries must be integer (got '$COMPARE_CONNECT_RETRIES')" >&2
  exit 2
fi
if ! [[ "$COMPARE_RETRY_SLEEP_SEC" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "ERROR: --retry-sleep-sec must be numeric (got '$COMPARE_RETRY_SLEEP_SEC')" >&2
  exit 2
fi

if [[ "$PREPARE_TEST_KB" == "true" && ! -f "$TEST_PDF_HOST" ]]; then
  echo "ERROR: test PDF not found on host: $TEST_PDF_HOST" >&2
  exit 2
fi

docker rm -f "$V4_CONTAINER" >/dev/null 2>&1 || true

cleanup() {
  if [[ "$KEEP_V4" != "true" ]]; then
    docker rm -f "$V4_CONTAINER" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

print_v4_diagnostics() {
  echo "[DIAG] v4 container state:"
  docker ps -a --filter "name=^${V4_CONTAINER}$" --format ' - {{.Names}} status={{.Status}}' || true
  docker inspect "$V4_CONTAINER" --format ' - status={{.State.Status}} exit={{.State.ExitCode}} oom={{.State.OOMKilled}} error={{.State.Error}} started={{.State.StartedAt}} finished={{.State.FinishedAt}}' 2>/dev/null || true
  echo "[DIAG] v4 container logs (tail 200):"
  docker logs --tail 200 "$V4_CONTAINER" 2>&1 || true
}

echo "[INFO] starting v4 container: $V4_CONTAINER"
echo "[INFO] v4 RAG device: $V4_RAG_DEVICE"
LOG_MAX_BYTES_CLEAN="$(read_env_int_from_file LOG_MAX_BYTES 10485760)"
LOG_BACKUP_COUNT_CLEAN="$(read_env_int_from_file LOG_BACKUP_COUNT 5)"
echo "[INFO] v4 logging env: LOG_MAX_BYTES=$LOG_MAX_BYTES_CLEAN LOG_BACKUP_COUNT=$LOG_BACKUP_COUNT_CLEAN"
V4_EXTRA_ENV=()
if [[ "${V4_RAG_DEVICE,,}" == cpu* ]]; then
  # Prevent accidental GPU allocation when compare is running side-by-side.
  V4_EXTRA_ENV+=(-e CUDA_VISIBLE_DEVICES=)
fi
docker run -d \
  --name "$V4_CONTAINER" \
  --network "container:${LEGACY_CONTAINER}" \
  --volumes-from "$LEGACY_CONTAINER" \
  --env-file .env \
  -e RAG_ORCHESTRATOR_V4=true \
  -e RAG_DEVICE="$V4_RAG_DEVICE" \
  -e LOG_MAX_BYTES="$LOG_MAX_BYTES_CLEAN" \
  -e LOG_BACKUP_COUNT="$LOG_BACKUP_COUNT_CLEAN" \
  "${V4_EXTRA_ENV[@]}" \
  "$IMAGE_NAME" \
  uvicorn backend.app:app --host 0.0.0.0 --port "$V4_PORT" --workers 1 >/dev/null

if [[ -z "$API_PREFIX" ]]; then
  API_PREFIX="$(docker exec "$LEGACY_CONTAINER" sh -lc 'printf "%s" "${BACKEND_API_PREFIX:-/api/v1}"')"
fi
if [[ -z "$API_PREFIX" ]]; then
  API_PREFIX="/api/v1"
fi

echo "[INFO] waiting for legacy health..."
for i in $(seq 1 60); do
  if docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:8000${API_PREFIX}/health", timeout=2)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
  then
    break
  fi
  sleep 2
done
if ! docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:8000${API_PREFIX}/health", timeout=5)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
then
  echo "ERROR: legacy health check failed (${LEGACY_CONTAINER})" >&2
  docker logs --tail 200 "$LEGACY_CONTAINER" 2>&1 || true
  exit 2
fi

echo "[INFO] compare endpoints: legacy=http://127.0.0.1:8000${API_PREFIX} v4=http://127.0.0.1:${V4_PORT}${API_PREFIX}"

echo "[INFO] waiting for v4 health..."
for i in $(seq 1 60); do
  if docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:${V4_PORT}/api/v1/health", timeout=2)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
  then
    break
  fi
  sleep 2
done

if ! docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:${V4_PORT}/api/v1/health", timeout=5)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
then
  echo "ERROR: v4 health check failed (${V4_CONTAINER})" >&2
  print_v4_diagnostics
  exit 2
fi

if [[ "$PREPARE_TEST_KB" == "true" ]]; then
  echo "[INFO] preparing test knowledge base and uploading PDF..."
  docker cp scripts/rag_prepare_test_kb.py "$LEGACY_CONTAINER:/tmp/rag_prepare_test_kb.py"
  docker cp "$TEST_PDF_HOST" "$LEGACY_CONTAINER:$TEST_PDF_CONTAINER"
  set +e
  PREP_OUTPUT="$(docker exec \
    "$LEGACY_CONTAINER" \
    python /tmp/rag_prepare_test_kb.py \
      --base-url http://127.0.0.1:8000 \
      --api-prefix "$API_PREFIX" \
      --kb-name "$TEST_KB_NAME" \
      --kb-description "$TEST_KB_DESCRIPTION" \
      --pdf-path "$TEST_PDF_CONTAINER" \
      --job-timeout-sec "$JOB_TIMEOUT_SEC" \
      --job-poll-sec "$JOB_POLL_SEC" 2>&1
)"
  prep_exit=$?
  set -e
  printf '%s\n' "$PREP_OUTPUT"
  if [[ $prep_exit -ne 0 ]]; then
    echo "ERROR: test KB preparation failed (exit=$prep_exit). See logs above." >&2
    exit "$prep_exit"
  fi
  PREP_KB_ID="$(printf '%s\n' "$PREP_OUTPUT" | tr -d '\r' | sed -n 's/.*KB_ID=\([0-9][0-9]*\).*/\1/p' | tail -n1)"
  if [[ -z "$PREP_KB_ID" ]]; then
    echo "ERROR: failed to parse KB_ID from preparation output (marker KB_ID=<int> not found)." >&2
    exit 2
  fi
  KB_ID="$PREP_KB_ID"
  echo "[INFO] prepared test KB id: $KB_ID"
fi

if [[ ! -f "$CASES_FILE_HOST" ]]; then
  echo "[WARN] cases file not found on host: $CASES_FILE_HOST"
  echo "[WARN] comparator will fail if no fallback cases are provided."
fi

docker cp scripts/rag_orchestrator_compare.py "$LEGACY_CONTAINER:/tmp/rag_orchestrator_compare.py"
if [[ -f "$CASES_FILE_HOST" ]]; then
  docker cp "$CASES_FILE_HOST" "$LEGACY_CONTAINER:/tmp/rag_eval.yaml"
fi

echo "[INFO] running comparator..."
CMD=(
  python /tmp/rag_orchestrator_compare.py
  --legacy-base-url http://127.0.0.1:8000
  --v4-base-url "http://127.0.0.1:${V4_PORT}"
  --api-prefix "$API_PREFIX"
  --connect-retries "$COMPARE_CONNECT_RETRIES"
  --retry-sleep-sec "$COMPARE_RETRY_SLEEP_SEC"
  --cases-file /tmp/rag_eval.yaml
  --json-out "$REPORT_PATH_CONTAINER"
  --max-source-hit-drop "$MAX_DROP"
)
if [[ -n "$KB_ID" ]]; then
  CMD+=(--kb-id "$KB_ID")
fi
if [[ "$PRINT_JSON" == "true" ]]; then
  CMD+=(--print-json)
fi

set +e
docker exec "$LEGACY_CONTAINER" "${CMD[@]}"
cmp_exit=$?
set -e
if [[ $cmp_exit -ne 0 ]]; then
  echo "[ERROR] comparator failed with exit code: $cmp_exit" >&2
  print_v4_diagnostics
  exit "$cmp_exit"
fi

echo "[INFO] done"
echo "[INFO] report in container: $REPORT_PATH_CONTAINER"
if [[ -n "$HOST_DATA_DIR" ]]; then
  report_name="$(basename "$REPORT_PATH_CONTAINER")"
  echo "[INFO] report on host (mounted): ${HOST_DATA_DIR}/${report_name}"
fi
