#!/usr/bin/env bash
set -euo pipefail

# Run legacy vs v4 RAG comparison in the current docker stack.
# - Reuses running legacy backend container
# - Starts temporary v4 backend container with RAG_ORCHESTRATOR_V4=true
# - Executes comparison from inside legacy container
# - Writes report to mounted /app/data (host: ./data by default)

LEGACY_CONTAINER="telegram_rag_backend"
V4_CONTAINER="telegram_rag_backend_v4"
V4_PORT="8001"
API_PREFIX=""
KB_ID=""
MAX_DROP="0.10"
CASES_FILE_HOST="tests/rag_eval.yaml"
REPORT_PATH_CONTAINER="/app/data/rag_compare_report.json"
KEEP_V4="false"
PRINT_JSON="true"
PREPARE_TEST_KB="false"
TEST_KB_NAME="rag_compare_test_kb"
TEST_KB_DESCRIPTION="Autogenerated by run_rag_compare_stack.sh"
TEST_PDF_HOST="test.pdf"
TEST_PDF_CONTAINER="/tmp/rag_compare_test.pdf"
JOB_TIMEOUT_SEC="600"
JOB_POLL_SEC="2"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run_rag_compare_stack.sh [options]

Options:
  --legacy-container <name>      Legacy backend container (default: telegram_rag_backend)
  --v4-container <name>          Temporary v4 container name (default: telegram_rag_backend_v4)
  --v4-port <port>               Port for temporary v4 backend in shared netns (default: 8001)
  --api-prefix <path>            API prefix (default: from container BACKEND_API_PREFIX or /api/v1)
  --kb-id <id>                   Knowledge base id (optional; auto-resolve if omitted)
  --prepare-test-kb              Recreate test KB and upload PDF before compare
  --test-kb-name <name>          Test KB name for --prepare-test-kb (default: rag_compare_test_kb)
  --test-pdf <path>              Host path to PDF for --prepare-test-kb (default: test.pdf)
  --job-timeout-sec <sec>        Wait timeout for ingestion job (default: 600)
  --job-poll-sec <sec>           Poll interval for ingestion job (default: 2)
  --cases-file <path>            Host path to eval cases file (default: tests/rag_eval.yaml)
  --report-path <path>           Container report path (default: /app/data/rag_compare_report.json)
  --max-source-hit-drop <float>  Fail if v4 source_hit drops more than value (default: 0.10)
  --keep-v4                      Keep temporary v4 container after run
  --no-print-json                Do not print full JSON report to stdout
  -h, --help                     Show help

Examples:
  bash scripts/run_rag_compare_stack.sh
  bash scripts/run_rag_compare_stack.sh --kb-id 1 --max-source-hit-drop 0.05
  bash scripts/run_rag_compare_stack.sh --prepare-test-kb --test-pdf test.pdf --max-source-hit-drop 0.10
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --legacy-container)
      LEGACY_CONTAINER="$2"
      shift 2
      ;;
    --v4-container)
      V4_CONTAINER="$2"
      shift 2
      ;;
    --v4-port)
      V4_PORT="$2"
      shift 2
      ;;
    --api-prefix)
      API_PREFIX="$2"
      shift 2
      ;;
    --kb-id)
      KB_ID="$2"
      shift 2
      ;;
    --prepare-test-kb)
      PREPARE_TEST_KB="true"
      shift
      ;;
    --test-kb-name)
      TEST_KB_NAME="$2"
      shift 2
      ;;
    --test-pdf)
      TEST_PDF_HOST="$2"
      shift 2
      ;;
    --job-timeout-sec)
      JOB_TIMEOUT_SEC="$2"
      shift 2
      ;;
    --job-poll-sec)
      JOB_POLL_SEC="$2"
      shift 2
      ;;
    --cases-file)
      CASES_FILE_HOST="$2"
      shift 2
      ;;
    --report-path)
      REPORT_PATH_CONTAINER="$2"
      shift 2
      ;;
    --max-source-hit-drop)
      MAX_DROP="$2"
      shift 2
      ;;
    --keep-v4)
      KEEP_V4="true"
      shift
      ;;
    --no-print-json)
      PRINT_JSON="false"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

if ! docker ps --format '{{.Names}}' | grep -qx "$LEGACY_CONTAINER"; then
  echo "ERROR: legacy container is not running: $LEGACY_CONTAINER" >&2
  echo "Running containers:" >&2
  docker ps --format ' - {{.Names}}' >&2
  exit 2
fi

if [[ ! -f .env ]]; then
  echo "ERROR: .env not found in current directory" >&2
  exit 2
fi

IMAGE_NAME="$(docker inspect "$LEGACY_CONTAINER" --format '{{.Config.Image}}' | tr -d '\r')"
HOST_DATA_DIR="$(docker inspect "$LEGACY_CONTAINER" --format '{{range .Mounts}}{{if eq .Destination "/app/data"}}{{println .Source}}{{end}}{{end}}' | tr -d '\r' | head -n1)"

if [[ -z "$IMAGE_NAME" ]]; then
  echo "ERROR: failed to resolve docker image for $LEGACY_CONTAINER" >&2
  exit 2
fi

if ! [[ "$V4_PORT" =~ ^[0-9]+$ ]]; then
  echo "ERROR: --v4-port must be numeric (got '$V4_PORT')" >&2
  exit 2
fi
if ! [[ "$JOB_TIMEOUT_SEC" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "ERROR: --job-timeout-sec must be numeric (got '$JOB_TIMEOUT_SEC')" >&2
  exit 2
fi
if ! [[ "$JOB_POLL_SEC" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
  echo "ERROR: --job-poll-sec must be numeric (got '$JOB_POLL_SEC')" >&2
  exit 2
fi

if [[ "$PREPARE_TEST_KB" == "true" && ! -f "$TEST_PDF_HOST" ]]; then
  echo "ERROR: test PDF not found on host: $TEST_PDF_HOST" >&2
  exit 2
fi

docker rm -f "$V4_CONTAINER" >/dev/null 2>&1 || true

cleanup() {
  if [[ "$KEEP_V4" != "true" ]]; then
    docker rm -f "$V4_CONTAINER" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

echo "[INFO] starting v4 container: $V4_CONTAINER"
docker run -d --rm \
  --name "$V4_CONTAINER" \
  --network "container:${LEGACY_CONTAINER}" \
  --volumes-from "$LEGACY_CONTAINER" \
  --env-file .env \
  -e RAG_ORCHESTRATOR_V4=true \
  "$IMAGE_NAME" \
  uvicorn backend.app:app --host 0.0.0.0 --port "$V4_PORT" --workers 1 >/dev/null

if [[ -z "$API_PREFIX" ]]; then
  API_PREFIX="$(docker exec "$LEGACY_CONTAINER" sh -lc 'printf "%s" "${BACKEND_API_PREFIX:-/api/v1}"')"
fi
if [[ -z "$API_PREFIX" ]]; then
  API_PREFIX="/api/v1"
fi
echo "[INFO] compare endpoints: legacy=http://127.0.0.1:8000${API_PREFIX} v4=http://127.0.0.1:${V4_PORT}${API_PREFIX}"

echo "[INFO] waiting for v4 health..."
for i in $(seq 1 60); do
  if docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:${V4_PORT}/api/v1/health", timeout=2)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
  then
    break
  fi
  sleep 2
done

if ! docker exec "$LEGACY_CONTAINER" python - <<PY >/dev/null 2>&1
import requests, sys
try:
    r = requests.get("http://127.0.0.1:${V4_PORT}/api/v1/health", timeout=5)
    sys.exit(0 if r.status_code == 200 else 1)
except Exception:
    sys.exit(1)
PY
then
  echo "ERROR: v4 health check failed (${V4_CONTAINER})" >&2
  exit 2
fi

if [[ "$PREPARE_TEST_KB" == "true" ]]; then
  echo "[INFO] preparing test knowledge base and uploading PDF..."
  docker cp "$TEST_PDF_HOST" "$LEGACY_CONTAINER:$TEST_PDF_CONTAINER"
  PREP_OUTPUT="$(docker exec \
    -e PREPARE_KB_NAME="$TEST_KB_NAME" \
    -e PREPARE_KB_DESCRIPTION="$TEST_KB_DESCRIPTION" \
    -e PREPARE_PDF_PATH="$TEST_PDF_CONTAINER" \
    -e PREPARE_API_PREFIX="$API_PREFIX" \
    -e PREPARE_JOB_TIMEOUT_SEC="$JOB_TIMEOUT_SEC" \
    -e PREPARE_JOB_POLL_SEC="$JOB_POLL_SEC" \
    "$LEGACY_CONTAINER" python - <<'PY'
import os
import sys
import time
from pathlib import Path
import requests

kb_name = os.getenv("PREPARE_KB_NAME", "rag_compare_test_kb").strip() or "rag_compare_test_kb"
kb_description = os.getenv("PREPARE_KB_DESCRIPTION", "").strip()
pdf_path = Path(os.getenv("PREPARE_PDF_PATH", "/tmp/rag_compare_test.pdf"))
api_prefix = (os.getenv("PREPARE_API_PREFIX", "/api/v1") or "/api/v1").strip("/")
job_timeout = float(os.getenv("PREPARE_JOB_TIMEOUT_SEC", "600") or "600")
job_poll = float(os.getenv("PREPARE_JOB_POLL_SEC", "2") or "2")

if not pdf_path.exists():
    print(f"[FAIL] test PDF is missing in container: {pdf_path}")
    raise SystemExit(2)

base_api = f"http://127.0.0.1:8000/{api_prefix}"
headers = {}
api_key = (os.getenv("BACKEND_API_KEY") or "").strip()
if api_key:
    headers["X-API-Key"] = api_key

def _request(method: str, url: str, **kwargs):
    resp = requests.request(method, url, headers=headers, timeout=30, **kwargs)
    if resp.status_code >= 400:
        body = (resp.text or "").strip()
        print(f"[FAIL] {method} {url} -> {resp.status_code}: {body[:500]}")
        raise SystemExit(2)
    return resp

print(f"[INFO] prep base_api={base_api} kb_name={kb_name}")
kbs_resp = _request("GET", f"{base_api}/knowledge-bases/")
kbs = kbs_resp.json() if kbs_resp.content else []
for kb in (kbs or []):
    if isinstance(kb, dict) and str(kb.get("name") or "") == kb_name:
        kb_id = kb.get("id")
        if kb_id is None:
            continue
        print(f"[INFO] deleting existing KB id={kb_id} name={kb_name}")
        _request("DELETE", f"{base_api}/knowledge-bases/{int(kb_id)}")

create_resp = _request(
    "POST",
    f"{base_api}/knowledge-bases/",
    json={"name": kb_name, "description": kb_description},
)
created = create_resp.json() if create_resp.content else {}
kb_id = int(created.get("id"))
print(f"[INFO] created KB id={kb_id} name={kb_name}")

with pdf_path.open("rb") as f:
    upload_resp = _request(
        "POST",
        f"{base_api}/ingestion/document",
        data={
            "knowledge_base_id": str(kb_id),
            "file_name": pdf_path.name,
            "file_type": "pdf",
            "telegram_id": "0",
            "username": "rag-compare-script",
        },
        files={"file": (pdf_path.name, f, "application/pdf")},
        timeout=180,
    )

upload_payload = upload_resp.json() if upload_resp.content else {}
job_id = upload_payload.get("job_id")
if not job_id:
    print(f"[FAIL] ingestion response does not contain job_id: {upload_payload}")
    raise SystemExit(2)

job_id = int(job_id)
print(f"[INFO] ingestion started job_id={job_id} file={pdf_path.name}")
deadline = time.time() + job_timeout
while time.time() < deadline:
    status_resp = _request("GET", f"{base_api}/jobs/{job_id}")
    payload = status_resp.json() if status_resp.content else {}
    status = str(payload.get("status") or "").strip().lower()
    progress = int(payload.get("progress") or 0)
    if status == "completed":
        print(f"[INFO] ingestion completed job_id={job_id} progress={progress}")
        print(f"KB_ID={kb_id}")
        raise SystemExit(0)
    if status == "failed":
        print(f"[FAIL] ingestion failed job_id={job_id}: {payload.get('error')}")
        raise SystemExit(2)
    time.sleep(max(0.2, job_poll))

print(f"[FAIL] timeout waiting for ingestion job_id={job_id} after {job_timeout:.1f}s")
raise SystemExit(2)
PY
)"
  printf '%s\n' "$PREP_OUTPUT"
  PREP_KB_ID="$(printf '%s\n' "$PREP_OUTPUT" | awk -F= '/^KB_ID=/{print $2}' | tail -n1 | tr -d '\r')"
  if [[ -z "$PREP_KB_ID" ]]; then
    echo "ERROR: failed to parse KB_ID from preparation output" >&2
    exit 2
  fi
  KB_ID="$PREP_KB_ID"
  echo "[INFO] prepared test KB id: $KB_ID"
fi

if [[ ! -f "$CASES_FILE_HOST" ]]; then
  echo "[WARN] cases file not found on host: $CASES_FILE_HOST"
  echo "[WARN] comparator will fail if no fallback cases are provided."
fi

docker cp scripts/rag_orchestrator_compare.py "$LEGACY_CONTAINER:/tmp/rag_orchestrator_compare.py"
if [[ -f "$CASES_FILE_HOST" ]]; then
  docker cp "$CASES_FILE_HOST" "$LEGACY_CONTAINER:/tmp/rag_eval.yaml"
fi

echo "[INFO] running comparator..."
CMD=(
  python /tmp/rag_orchestrator_compare.py
  --legacy-base-url http://127.0.0.1:8000
  --v4-base-url "http://127.0.0.1:${V4_PORT}"
  --api-prefix "$API_PREFIX"
  --cases-file /tmp/rag_eval.yaml
  --json-out "$REPORT_PATH_CONTAINER"
  --max-source-hit-drop "$MAX_DROP"
)
if [[ -n "$KB_ID" ]]; then
  CMD+=(--kb-id "$KB_ID")
fi
if [[ "$PRINT_JSON" == "true" ]]; then
  CMD+=(--print-json)
fi

docker exec "$LEGACY_CONTAINER" "${CMD[@]}"

echo "[INFO] done"
echo "[INFO] report in container: $REPORT_PATH_CONTAINER"
if [[ -n "$HOST_DATA_DIR" ]]; then
  report_name="$(basename "$REPORT_PATH_CONTAINER")"
  echo "[INFO] report on host (mounted): ${HOST_DATA_DIR}/${report_name}"
fi
